{% set name = "lucky-commit" %}
{% set version = "2.2.5" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://github.com/not-an-aardvark/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: cab69b87afac8b2e8db3949397695809977199ccc4894b8af53e59da7f917126

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - ocl-icd  # [linux]
    - khronos-opencl-icd-loader  # [win or osx]
  run:
    - ocl-icd  # [linux]
    - khronos-opencl-icd-loader  # [win or osx]

test:
  commands:
    - lucky_commit --benchmark

about:
  home: https://github.com/not-an-aardvark/lucky-commit
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE.md
    - THIRDPARTY_LICENSES.yaml
  summary: Customize your git commit hashes!

extra:
  recipe-maintainers:
    - pavelzw
